const glyphs=['🀇','🀈','🀉','🀊','🀋','🀌','🀍','🀎','🀏','🀙','🀚','🀛','🀜','🀝','🀞','🀟','🀠','🀡','🀐','🀑','🀒','🀓','🀔','🀕','🀖','🀗','🀘','🀀','🀁','🀂','🀃','🀆','🀅','🀄'];
let hand=[],running=false,visualDone=0,visualTarget=null,visualTimer=null;
const $=id=>document.getElementById(id);
function render(){ $('hand').innerHTML=hand.map((t,i)=>`<button class="tile" data-i="${i}">${glyphs[t]}</button>`).join(''); $('run').classList.toggle('disabled',hand.length!==13||running); }
function deck(){return Array.from({length:34},(_,i)=>Array(4).fill(i)).flat()}
function shuffle(a){for(let i=a.length-1;i;i--){const j=(Math.random()*(i+1))|0;[a[i],a[j]]=[a[j],a[i]]}return a}
function deal(){hand=shuffle(deck()).slice(0,13).sort((a,b)=>a-b);render()}
function add(t){if(hand.length>=13||hand.filter(x=>x===t).length>=4)return;hand.push(t);hand.sort((a,b)=>a-b);render()}
function counts(){const c=Array(34).fill(0);for(const t of hand)c[t]++;return c}
function margin(w,n){if(!n)return 1;const p=w/n;return 1.96*Math.sqrt(Math.max(.000001,p*(1-p))/n)}
function paint(a,total,label='計算中'){const n=a.done;if(!n)return;$('bar').style.width=Math.min(100,n/total*100)+'%';$('status').textContent=`${label}… ${n.toLocaleString()} / ${total.toLocaleString()}`;$('solo').textContent=(a.solo/n*100).toFixed(1)+'%';$('table').textContent=(a.table/n*100).toFixed(1)+'%';$('tenpai').textContent=(a.ten/n*100).toFixed(1)+'%';$('turn').textContent=a.turnN?(a.turnSum/a.turnN).toFixed(1)+'巡':'—';$('soloCi').textContent=`95%誤差幅 ±${(margin(a.solo,n)*100).toFixed(1)}pt`;$('tableCi').textContent=`95%誤差幅 ±${(margin(a.table,n)*100).toFixed(1)}pt`;$('tenpaiCi').textContent=`95%誤差幅 ±${(margin(a.ten,n)*100).toFixed(1)}pt`}
function setVisualTarget(a,total){visualTarget={...a,total};if(visualTimer)return;const tick=()=>{visualTimer=null;if(!visualTarget)return;if(visualDone<visualTarget.done){visualDone++;const r=visualDone/visualTarget.done;paint({done:visualDone,solo:visualTarget.solo*r,table:visualTarget.table*r,ten:visualTarget.ten*r,turnSum:visualTarget.turnSum*r,turnN:visualTarget.turnN*r},visualTarget.total);const gap=visualTarget.done-visualDone;visualTimer=setTimeout(tick,gap>500?0:gap>100?2:8)}};visualTimer=setTimeout(tick,0)}
function renderYaku(yaku,wins,unknown=0,riichi=0,tsumo=0){$('riichiCount').textContent=riichi;$('tsumoCount').textContent=tsumo;const rows=Object.entries(yaku||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);if(!rows.length)$('yakuRank').innerHTML='<div class="empty">役を判定できる和了がまだありません。</div>';else{const max=rows[0][1];$('yakuRank').innerHTML=rows.map(([name,n],i)=>`<div class="rank-row"><span class="rank-num">${i+1}</span><span class="rank-name">${name}</span><span class="rank-bar"><i style="width:${(n/max*100).toFixed(1)}%"></i></span><span class="rank-val">${n}回 (${wins?(n/wins*100).toFixed(1):'0.0'}%)</span></div>`).join('')}$('yakuUnknown').textContent=unknown?`判定不能: ${unknown}和了`:''}
const hw=navigator.hardwareConcurrency||2,cores=hw>=8?4:hw>=6?3:hw>=4?2:1;$('workerBadge').textContent=`${cores}並列 Worker / ${hw}論理コア`;
function runWorker(w,h,n,id,progress){return new Promise((resolve,reject)=>{const fn=e=>{if(e.data.id!==id)return;if(typeof e.data.wasm==='boolean')$('wasmBadge').textContent=e.data.wasm?'WASM有効':'JS fallback';if(e.data.type==='progress')progress(e.data);if(e.data.type==='done'){w.removeEventListener('message',fn);resolve(e.data)}};w.addEventListener('message',fn);w.addEventListener('error',reject,{once:true});w.postMessage({hand:h,trials:n,id})})}
async function run(){if(hand.length!==13||running)return;running=true;render();$('wasmBadge').textContent='WASM起動中';$('yakuRank').innerHTML='<div class="empty">集計中…</div>';$('yakuUnknown').textContent='';$('riichiCount').textContent='0';$('tsumoCount').textContent='0';visualDone=0;visualTarget=null;if(visualTimer){clearTimeout(visualTimer);visualTimer=null}for(const id of ['solo','table','tenpai','turn'])$(id).textContent='—';for(const id of ['soloCi','tableCi','tenpaiCi'])$(id).textContent='95%誤差幅 —';$('bar').style.width='0%';
 const requested=+$('trials').value,h=counts(),workers=Array.from({length:cores},()=>new Worker('./worker.js?v=0.9.6'));let total={done:0,solo:0,table:0,ten:0,turnSum:0,turnN:0,yaku:{},unknown:0,riichi:0,tsumo:0},assigned=0,jobId=0;const chunk=requested>=10000?1000:requested>=2000?500:125,active=new Map();
 function aggregate(){const a={done:total.done,solo:total.solo,table:total.table,ten:total.ten,turnSum:total.turnSum,turnN:total.turnN};for(const p of active.values()){a.done+=p.done;a.solo+=p.solo;a.table+=p.table;a.ten+=p.ten;a.turnSum+=p.turnSum;a.turnN+=p.turnN}return a}
 function stats(){const y={...total.yaku};let u=total.unknown,r=total.riichi,t=total.tsumo;for(const p of active.values()){for(const [name,n] of Object.entries(p.yaku||{}))y[name]=(y[name]||0)+n;u+=p.unknown||0;r+=p.riichi||0;t+=p.tsumo||0}return{y,u,r,t}}
 async function pump(w){while(assigned<requested){const take=Math.min(chunk,requested-assigned);assigned+=take;const id=++jobId;active.set(id,{done:0,solo:0,table:0,ten:0,turnSum:0,turnN:0,yaku:{},unknown:0,riichi:0,tsumo:0});const r=await runWorker(w,h,take,id,p=>{active.set(id,p);const a=aggregate(),s=stats();setVisualTarget(a,requested);renderYaku(s.y,a.table,s.u,s.r,s.t)});active.delete(id);total.done+=r.done;total.solo+=r.solo;total.table+=r.table;total.ten+=r.ten;total.turnSum+=r.turnSum;total.turnN+=r.turnN;total.unknown+=r.unknown||0;total.riichi+=r.riichi||0;total.tsumo+=r.tsumo||0;for(const [name,n] of Object.entries(r.yaku||{}))total.yaku[name]=(total.yaku[name]||0)+n;const a=aggregate(),s=stats();setVisualTarget(a,requested);renderYaku(s.y,a.table,s.u,s.r,s.t)}}
 try{await Promise.all(workers.map(pump));if(visualTimer){clearTimeout(visualTimer);visualTimer=null}visualDone=total.done;paint(total,total.done,'完了');renderYaku(total.yaku,total.table,total.unknown,total.riichi,total.tsumo);$('status').textContent=`${total.done.toLocaleString()}局 × 2モデルを完了しました。`;$('bar').style.width='100%'}catch(e){console.error(e);$('status').textContent='計算中にエラーが発生しました。'}finally{workers.forEach(w=>w.terminate());running=false;render()}}
for(let i=0;i<27;i++)$('suits').insertAdjacentHTML('beforeend',`<button class="tile" data-t="${i}">${glyphs[i]}</button>`);for(let i=27;i<34;i++)$('honors').insertAdjacentHTML('beforeend',`<button class="tile" data-t="${i}">${glyphs[i]}</button>`);
$('picker').onclick=e=>{const b=e.target.closest('[data-t]');if(b)add(+b.dataset.t)};$('hand').onclick=e=>{const b=e.target.closest('[data-i]');if(b&&!running){hand.splice(+b.dataset.i,1);render()}};$('randomTab').onclick=()=>{$('randomTab').className='on';$('selectTab').className='';$('picker').hidden=true};$('selectTab').onclick=()=>{$('selectTab').className='on';$('randomTab').className='';$('picker').hidden=false};$('deal').onclick=()=>{if(!running)deal()};$('clear').onclick=()=>{if(!running){hand=[];render()}};$('run').onclick=run;
let lastTouchEnd=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=now},{passive:false});deal();render();