const WASM_B64='AGFzbQEAAAABDgJgAX8Bf2AFf39/f38AAwMCAAEEBQFwAQEBBQQBAQICBggBfwFBkIgECwcUAgZtZW1vcnkCAAdzaGFudGVuAAAK5gkCyQQBEX8jgICAgABBMGsiASSAgICAAEEAQQg2AoCIgIAAIAFBIGogAEEgai8AADsBACABQRhqIABBGGopAAA3AwAgAUEQaiAAQRBqKQAANwMAIAEgACkAADcDACABIABBCGopAAA3AwggAUEAQQBBAEEAEIGAgIAAQQAoAoCIgIAAIQJBACEDQQAhBEEAIQUDQCADIAAgBWoiBi0AACIHQQFLaiAGQQFqLQAAIgZBAUtqIQMgBCAHQQBHaiAGQQBHaiEEIAVBAmoiBUEiRw0ACyAALQAIIQYgAC0AACEHIAAtAAkhCCAALQARIQkgAC0AEiEKIAAtABohCyAALQAbIQwgAC0AHCENIAAtAB0hDiAALQAeIQ8gAC0AHyEQIAAtACAhESAALQAhIQUgAUEwaiSAgICAAEF/QQAgBkH/AXEiBhsgB0H/AXEiB0EAR2sgCEH/AXEiAEEAR2sgCUH/AXEiAUEAR2sgCkH/AXEiCEEAR2sgC0H/AXEiCUEAR2sgDEH/AXEiCkEAR2sgDUH/AXEiC0EAR2sgDkH/AXEiDEEAR2sgD0H/AXEiDUEAR2sgEEH/AXEiDkEAR2sgEUH/AXEiD0EAR2sgBUEAR2sgBUEBSyAPQQFLciAOQQFLciANQQFLciAMQQFLciALQQFLciAKQQFLciAJQQFLciAIQQFLciABQQFLciAAQQFLciAGQQFLciAHQQFLckEBcWtBDWoiBUEGIANrIgMgBGtBB2ogAyAEQQdJGyIEIAIgBCACSBsiBCAFIARIGwuYBQEIfwJAAkACQCABQSFKDQADQCAAIAFqIgUtAAAiBg0CIAFBAWoiAUEiRw0ACwtBCCACQQF0QQQgAmsiASADIAEgA0gbaiAEamsiAUEAKAKAiICAAE4NAUEAIAE2AoCIgIAADwsgAkEESg0AIANBBEoNAAJAIAZBA0kNACAFIAZBfWo6AAAgACABIAJBAWogAyAEEIGAgIAAIAUgBS0AAEEDaiIGOgAACwJAIAFBG0ggAUEJbyIHQQdIcSIIQQFHDQAgBUEBai0AACIJRQ0AIAVBAmoiCi0AACILRQ0AIAVBAWoiDCAJQX9qOgAAIAUgBkF/ajoAACAKIAtBf2o6AAAgACABIAJBAWogAyAEEIGAgIAAIAUgBS0AAEEBaiIGOgAAIAwgDC0AAEEBajoAACAKIAotAABBAWo6AAALAkACQCAEDQAgBkH/AXFBAkkNASAFIAZBfmo6AAAgACABIAIgA0EBEIGAgIAAIAUgBS0AAEECaiIGOgAACyAGQf8BcUECSQ0AIAUgBkF+ajoAACAAIAEgAiADQQFqIAQQgYCAgAAgBSAFLQAAQQJqIgY6AAALAkAgAUEaSg0AIAdBB0oNACAFQQFqIggtAAAiCkUNACAHIApBf2o6AAAgBSAGQX9qOgAAIAAgASACIANBAWogBBCBgICAACAFIAUtAABBAWoiBjoAACAHIActAABBAWo6AAALAkAgCEUNACAFQQJqIggtAAAiB0UNACAIIAdBf2o6AAAgBSAGQX9qOgAAIAAgASACIANBAWogBBCBgICAACAFIAUtAABBAWoiBjoAACAIIAgtAABBAWo6AAALIAUgBkF/ajoAACAAIAEgAiADIAQQgYCAgAAgBSAFLQAAQQFqOgAACws=';
const kokushiTiles=[0,8,9,17,18,26,27,28,29,30,31,32,33];
const shantenCache=new Map(),effectiveCache=new Map(),discardCache=new Map(),blockCache=new Map();
let wasmShanten=null;
try{const raw=atob(WASM_B64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const inst=new WebAssembly.Instance(new WebAssembly.Module(bytes),{}),mem=new Uint8Array(inst.exports.memory.buffer,0,34);wasmShanten=c=>{mem.set(c);return inst.exports.shanten(0)}}catch(e){wasmShanten=null}
function key(c){let s='';for(let i=0;i<34;i++)s+=String.fromCharCode(48+c[i]);return s}
function encodeBlock(c,start,len){let n=0,m=1;for(let i=0;i<len;i++){n+=c[start+i]*m;m*=5}return n}
function blockOptions(c,start,len,suited){const code=encodeBlock(c,start,len),cacheKey=(suited?'s':'h')+code;const hit=blockCache.get(cacheKey);if(hit)return hit;const a=new Uint8Array(len);for(let i=0;i<len;i++)a[i]=c[start+i];const states=new Map();function add(m,t,p){states.set(m+','+t+','+p,[m,t,p])}function dfs(i,m,t,p){while(i<len&&!a[i])i++;if(i===len){add(m,t,p);return}if(a[i]>=3){a[i]-=3;dfs(i,m+1,t,p);a[i]+=3}if(suited&&i<=len-3&&a[i+1]&&a[i+2]){a[i]--;a[i+1]--;a[i+2]--;dfs(i,m+1,t,p);a[i]++;a[i+1]++;a[i+2]++}if(a[i]>=2){a[i]-=2;dfs(i,m,t,p+1);a[i]+=2}if(suited&&i<=len-2&&a[i+1]){a[i]--;a[i+1]--;dfs(i,m,t+1,p);a[i]++;a[i+1]++}if(suited&&i<=len-3&&a[i+2]){a[i]--;a[i+2]--;dfs(i,m,t+1,p);a[i]++;a[i+2]++}a[i]--;dfs(i,m,t,p);a[i]++}dfs(0,0,0,0);const opts=[...states.values()];blockCache.set(cacheKey,opts);return opts}
function standard(c){const blocks=[blockOptions(c,0,9,true),blockOptions(c,9,9,true),blockOptions(c,18,9,true),blockOptions(c,27,7,false)];let combos=[[0,0,0]];for(const opts of blocks){const next=[];for(const a of combos)for(const b of opts)next.push([a[0]+b[0],a[1]+b[1],a[2]+b[2]]);combos=next}let best=8;for(const [m0,t0,pairs] of combos){const m=Math.min(4,m0);for(let head=0;head<=Math.min(1,pairs);head++){let t=t0+(pairs-head);t=Math.min(t,4-m);const s=8-m*2-t-head;if(s<best)best=s}}return best}
function chiitoi(c){let pairs=0,unique=0;for(let i=0;i<34;i++){if(c[i])unique++;if(c[i]>=2)pairs++}return 6-pairs+Math.max(0,7-unique)}
function kokushi(c){let unique=0,pair=0;for(const i of kokushiTiles){if(c[i])unique++;if(c[i]>=2)pair=1}return 13-unique-pair}
function shanten(c){const k=key(c),hit=shantenCache.get(k);if(hit!==undefined)return hit;const v=wasmShanten?wasmShanten(c):Math.min(standard(c),chiitoi(c),kokushi(c));if(shantenCache.size<320000)shantenCache.set(k,v);return v}
function effective(c,base){const k=key(c)+'|'+base,hit=effectiveCache.get(k);if(hit!==undefined)return hit;let n=0;for(let t=0;t<34;t++){if(c[t]>=4)continue;c[t]++;if(shanten(c)<base)n+=5-c[t];c[t]--}if(effectiveCache.size<200000)effectiveCache.set(k,n);return n}
function shape(c){let s=0;for(let i=0;i<34;i++){if(c[i]>=2)s+=2.5;if(i<27){const r=i%9;if(r<8&&c[i]&&c[i+1])s+=1.4;if(r<7&&c[i]&&c[i+2])s+=.8;if(c[i]&&r>=2&&r<=6)s+=.12}else if(c[i]===1)s-=.35}return s}
function discard(c){const k=key(c),cached=discardCache.get(k);if(cached!==undefined&&c[cached])return cached;let best=-1,bestS=99,bestU=-1,bestShape=-999;for(let t=0;t<34;t++){if(!c[t])continue;c[t]--;const s=shanten(c),u=s<=2?effective(c,s):0,sp=shape(c);c[t]++;if(s<bestS||(s===bestS&&u>bestU)||(s===bestS&&u===bestU&&sp>bestShape)){best=t;bestS=s;bestU=u;bestShape=sp}}if(discardCache.size<200000)discardCache.set(k,best);return best}
function draw(wall,total){let r=Math.floor(Math.random()*total);for(let i=0;i<34;i++){const n=wall[i];if(r<n){wall[i]--;return i}r-=n}return -1}
function makeWall(known){const w=new Uint8Array(34);w.fill(4);let total=136;for(let i=0;i<34;i++){w[i]-=known[i];total-=known[i]}return[w,total]}
function dealOpponent(wall,total){const h=new Uint8Array(34);for(let i=0;i<13;i++){const t=draw(wall,total--);h[t]++}return[h,total]}
function simulate(known,withOpp){let[wall,total]=makeWall(known);const me=Uint8Array.from(known),opp=[];if(withOpp)for(let p=0;p<3;p++){let h;[h,total]=dealOpponent(wall,total);opp.push(h)}let ten=shanten(me)===0;for(let turn=1;turn<=18&&total>0;turn++){let t=draw(wall,total--);me[t]++;if(shanten(me)===-1)return{win:1,ten:1,turn};me[discard(me)]--;if(shanten(me)===0)ten=true;if(withOpp)for(let p=0;p<3&&total>0;p++){const h=opp[p];t=draw(wall,total--);h[t]++;if(shanten(h)===-1)return{win:0,ten:ten?1:0,turn};h[discard(h)]--}}return{win:0,ten:ten?1:0,turn:0}}
self.onmessage=e=>{const{hand,trials,id}=e.data,known=Uint8Array.from(hand);let solo=0,table=0,ten=0,turnSum=0,turnN=0;for(let i=1;i<=trials;i++){const a=simulate(known,false),b=simulate(known,true);solo+=a.win;table+=b.win;ten+=b.ten;if(b.win){turnSum+=b.turn;turnN++}if(i%20===0||i===trials)postMessage({type:'progress',id,done:i,solo,table,ten,turnSum,turnN,wasm:!!wasmShanten})}postMessage({type:'done',id,done:trials,solo,table,ten,turnSum,turnN,wasm:!!wasmShanten})};