const $=s=>document.querySelector(s);
const grid=$('#grid'),timeEl=$('#time'),nextEl=$('#next'),bestEl=$('#best'),progressEl=$('#progress'),messageEl=$('#message');
const startButton=$('#start'),resetBestButton=$('#resetBest'),sizeDown=$('#sizeDown'),sizeUp=$('#sizeUp'),sizeLabel=$('#sizeLabel'),totalLabel=$('#totalLabel');
const fillMode=$('#fillMode'),rotateMode=$('#rotateMode'),moveMode=$('#moveMode'),modeName=$('#modeName');
let gridSize=5,total=25,expected=1,playing=false,startedAt=0,animationId=0,board=[],rotation=0;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function ruleCode(){return `${fillMode.checked?'F':'N'}${rotateMode.checked?'R':'N'}${moveMode.checked?'M':'N'}`}
function bestKey(){return `numberTapBest-${gridSize}-${ruleCode()}`}
function getBest(){const v=Number(localStorage.getItem(bestKey()));return Number.isFinite(v)&&v>0?v:null}
function showBest(){const v=getBest();bestEl.textContent=v?v.toFixed(2):'--'}
function updateModeName(){const n=[fillMode,rotateMode,moveMode].filter(x=>x.checked).length;modeName.textContent=['NORMAL','HARD','EXPERT','MASTER'][n];showBest()}
function setSettingsDisabled(disabled){fillMode.disabled=disabled;rotateMode.disabled=disabled;moveMode.disabled=disabled;sizeDown.disabled=disabled||gridSize<=3;sizeUp.disabled=disabled||gridSize>=10}
function createBoard(){board=shuffle(Array.from({length:total},(_,i)=>i+1));rotation=0;grid.style.transform='rotate(0deg)'}
function renderGrid(enabled=false){grid.replaceChildren();for(const value of board){if(value===null){const hole=document.createElement('span');hole.className='number-button done';hole.setAttribute('aria-hidden','true');grid.append(hole);continue}const b=document.createElement('button');b.className='number-button';b.type='button';b.textContent=value;b.disabled=!enabled;b.setAttribute('aria-label',String(value));b.addEventListener('pointerdown',e=>{e.preventDefault();handleTap(b,value)},{passive:false});grid.append(b)}}
function updateSizeUi(){total=gridSize*gridSize;sizeLabel.textContent=`${gridSize}×${gridSize}`;totalLabel.textContent=`1〜${total}`;progressEl.textContent=`0 / ${total}`;nextEl.textContent='1';grid.style.setProperty('--grid-size',gridSize);grid.style.setProperty('--grid-gap',`${Math.max(2,8-gridSize*.65)}px`);grid.style.setProperty('--number-size',`${Math.max(11,29-gridSize*1.7)}px`);setSettingsDisabled(false);showBest();createBoard();renderGrid(false)}
function updateTimer(){if(!playing)return;timeEl.textContent=((performance.now()-startedAt)/1000).toFixed(2);animationId=requestAnimationFrame(updateTimer)}
function moveSomeNumbers(){const positions=board.map((v,i)=>v===null?null:i).filter(v=>v!==null);const selected=shuffle([...positions]).slice(0,Math.min(5,positions.length));const values=shuffle(selected.map(i=>board[i]));selected.forEach((p,i)=>board[p]=values[i])}
function rotateBoard(){const turns=[90,180,270];rotation=(rotation+turns[Math.floor(Math.random()*turns.length)])%360;grid.style.transform=`rotate(${rotation}deg) scale(.95)`;setTimeout(()=>grid.style.transform=`rotate(${rotation}deg)`,180)}
function handleTap(button,number){if(!playing)return;if(number!==expected){button.classList.remove('wrong');void button.offsetWidth;button.classList.add('wrong');navigator.vibrate?.(20);return}const index=board.indexOf(number);if(fillMode.checked){board.splice(index,1);board.push(null)}else board[index]=null;progressEl.textContent=`${number} / ${total}`;if(number===total){finishGame();return}expected++;nextEl.textContent=expected;messageEl.textContent=`${expected} をタップ！`;if(moveMode.checked)moveSomeNumbers();renderGrid(true);if(rotateMode.checked&&number%5===0)rotateBoard()}
function startGame(){cancelAnimationFrame(animationId);expected=1;playing=true;timeEl.textContent='0.00';nextEl.textContent='1';progressEl.textContent=`0 / ${total}`;messageEl.textContent='1 をタップ！';startButton.textContent='やり直す';setSettingsDisabled(true);createBoard();renderGrid(true);startedAt=performance.now();updateTimer()}
function finishGame(){playing=false;cancelAnimationFrame(animationId);const result=(performance.now()-startedAt)/1000;timeEl.textContent=result.toFixed(2);nextEl.textContent='✓';progressEl.textContent=`${total} / ${total}`;const old=getBest(),isNew=!old||result<old;if(isNew)localStorage.setItem(bestKey(),String(result));showBest();messageEl.textContent=isNew?`新記録！ ${result.toFixed(2)}秒`:`クリア！ ${result.toFixed(2)}秒`;startButton.textContent='もう一度';setSettingsDisabled(false);renderGrid(false);navigator.vibrate?.([40,40,80])}
function changeSize(delta){if(playing)return;const next=Math.min(10,Math.max(3,gridSize+delta));if(next===gridSize)return;gridSize=next;timeEl.textContent='0.00';messageEl.textContent='サイズとルールを選んでスタート！';updateSizeUi()}
startButton.addEventListener('click',startGame);sizeDown.addEventListener('click',()=>changeSize(-1));sizeUp.addEventListener('click',()=>changeSize(1));
[fillMode,rotateMode,moveMode].forEach(input=>input.addEventListener('change',()=>{updateModeName();messageEl.textContent='ルールを変更しました'}));
resetBestButton.addEventListener('click',()=>{localStorage.removeItem(bestKey());showBest();messageEl.textContent='現在の条件のベストを削除しました'});
updateModeName();updateSizeUi();
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();if('caches'in window){for(const key of await caches.keys())await caches.delete(key)}})}