from __future__ import annotations

import html
import re
import time
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

FANY = "https://ticket.fany.lol"
OUT = Path(__file__).resolve().parents[1] / "auto-data.js"
UA = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124 Safari/537.36 YoshimotoTokyoLiveUpdater/2.0"
}

# FANYの「劇場から探す」に掲載されている東京都内の常設劇場。
VENUES = {
    "lumine": ("ルミネtheよしもと", "新宿"),
    "shibuya_manzaigekijyo": ("渋谷よしもと漫才劇場", "渋谷"),
    "jimbocho_manzaigekijyo": ("神保町よしもと漫才劇場", "神保町"),
    "roppongi": ("YOSHIMOTO ROPPONGI THEATER", "六本木"),
}

SESSION = requests.Session()
SESSION.headers.update(UA)


def clean(text: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(text or "")).strip()


def get(url: str) -> requests.Response:
    response = SESSION.get(url, timeout=30)
    response.raise_for_status()
    return response


def same_venue_page(href: str, slug: str) -> bool:
    if not href:
        return False
    absolute = urljoin(FANY, href)
    parsed = urlparse(absolute)
    return parsed.netloc == "ticket.fany.lol" and parsed.path.rstrip("/") == f"/{slug}"


def collect_event_links_from_page(url: str, slug: str) -> tuple[set[str], set[str]]:
    """Return (event detail links, additional same-venue list pages)."""
    soup = BeautifulSoup(get(url).text, "html.parser")
    events: set[str] = set()
    pages: set[str] = set()

    for anchor in soup.find_all("a", href=True):
        href = anchor.get("href", "")
        absolute = urljoin(FANY, href)
        parsed = urlparse(absolute)

        if parsed.netloc != "ticket.fany.lol":
            continue
        if parsed.path.startswith("/event/detail/"):
            events.add(absolute.split("#", 1)[0])
            continue
        if same_venue_page(href, slug) and absolute != url:
            # pagination / filters generated by FANY are safe to crawl, but cap below.
            pages.add(absolute.split("#", 1)[0])

    return events, pages


def find_detail_links() -> dict[str, tuple[str, str]]:
    """Collect event detail URLs directly from every Tokyo FANY venue page.

    The old implementation crawled live.yoshimoto.co.jp and therefore missed many
    FANY-only listings. We now crawl each venue's FANY listing and discover its
    pagination/filter links as well.
    """
    found: dict[str, tuple[str, str]] = {}

    for slug, (venue, area) in VENUES.items():
        seed = f"{FANY}/{slug}"
        queue = [seed]
        visited: set[str] = set()
        page_count = 0

        while queue and page_count < 20:
            url = queue.pop(0)
            if url in visited:
                continue
            visited.add(url)
            page_count += 1

            try:
                event_links, more_pages = collect_event_links_from_page(url, slug)
            except Exception as exc:
                print(f"WARN listing {url}: {exc}")
                continue

            for event_url in event_links:
                found[event_url] = (venue, area)

            # Prefer links that actually look like pagination/search variants and
            # avoid endlessly crawling every arbitrary filter combination.
            for candidate in sorted(more_pages):
                if candidate in visited or candidate in queue:
                    continue
                if any(token in candidate for token in ("page=", "?from=", "search_type=form", "ngk_")):
                    queue.append(candidate)

        print(f"{venue}: {sum(1 for value in found.values() if value[0] == venue)} detail links from {page_count} listing pages")

    return found


def parse_date(text: str) -> str | None:
    # FANY detail pages use either 2026/08/25 or 2026年8月25日 depending on template.
    match = re.search(r"(20\d{2})[年/]\s*(\d{1,2})[月/]\s*(\d{1,2})日?", text)
    if not match:
        return None
    return f"{int(match.group(1)):04d}-{int(match.group(2)):02d}-{int(match.group(3)):02d}"


def parse_time_pair(text: str) -> tuple[str, str]:
    open_match = re.search(r"開場\s*(\d{1,2}:\d{2})|(?:\d{1,2}:\d{2})\s*開場", text)
    start_match = re.search(r"開演\s*(\d{1,2}:\d{2})|(?:\d{1,2}:\d{2})\s*開演", text)

    # Handle both "開場 17:15" and "17:15 開場" without relying on one template.
    open2 = re.search(r"(\d{1,2}:\d{2})\s*開場", text)
    start2 = re.search(r"(\d{1,2}:\d{2})\s*開演", text)
    open_time = (open_match.group(1) if open_match and open_match.group(1) else None) or (open2.group(1) if open2 else "")
    start_time = (start_match.group(1) if start_match and start_match.group(1) else None) or (start2.group(1) if start2 else "")
    return open_time, start_time


def parse_price(text: str) -> tuple[str, str]:
    candidates: list[int] = []
    for pattern in (
        r"(?:前売|一般|料金|指定席|自由席)[^\d]{0,30}([0-9,]{3,6})円",
        r"([0-9,]{3,6})円",
    ):
        for value in re.findall(pattern, text):
            price = int(value.replace(",", ""))
            if 500 <= price <= 30000:
                candidates.append(price)
        if candidates:
            break
    if not candidates:
        return "", "価格は公式で確認"
    price = min(candidates)
    return str(price), f"前売 {price:,}円"


def infer_genre(title: str, text: str) -> str:
    source = f"{title} {text[:1200]}"
    if any(word in source for word in ("寄席", "お笑いライブ", "漫才ライブ", "ネタライブ", "ネタ出演者")):
        return "neta"
    if any(word in source for word in ("ネタ＆コーナー", "ネタ&コーナー", "コーナーライブ")):
        return "neta-corner"
    if "コント" in source:
        return "conte"
    return "project"


def extract_title(soup: BeautifulSoup, text: str) -> str:
    # Structured detail templates generally expose the name after 公演名.
    match = re.search(r"公演名\s+(.+?)(?:日程|日時|会場名)", text)
    if match:
        return clean(match.group(1))

    # Older FANY template places title between the date and 開場.
    match = re.search(r"20\d{2}/\d{1,2}/\d{1,2}[^ ]*\s+(.+?)\s+開場", text)
    if match:
        return clean(match.group(1))

    node = soup.find("h1") or soup.find("h2")
    return clean(node.get_text(" ") if node else "")


def extract_performers(text: str) -> str:
    match = re.search(r"出演者\s+(.+?)(?:注意事項|受付|チケット|料金|販売|お問い合わせ)", text)
    if not match:
        return "出演者は公式で確認"
    value = clean(match.group(1))
    value = re.sub(r"\[(?:ネタ出演者|企画ライブ|ネタ＆コーナーライブ|コーナー出演者)\]", "", value)
    value = value.replace("、", "／")
    return value[:900] or "出演者は公式で確認"


def parse_detail(url: str, fallback_venue: str, fallback_area: str, today: str, horizon: str) -> str | None:
    soup = BeautifulSoup(get(url).text, "html.parser")
    text = clean(soup.get_text(" "))

    date = parse_date(text)
    if not date or date < today or date > horizon:
        return None

    open_time, start_time = parse_time_pair(text)
    if not start_time:
        return None

    title = extract_title(soup, text)
    if not title:
        return None

    venue = fallback_venue
    area = fallback_area
    venue_match = re.search(r"会場名\s+(.+?)(?:出演者|注意事項|受付)", text)
    if venue_match:
        detected = clean(venue_match.group(1)).replace("(東京都)", "").replace("（東京都）", "")
        if detected:
            venue = detected

    performers = extract_performers(text)
    price, price_text = parse_price(text)
    genre = infer_genre(title, text)
    status = "available" if any(word in text for word in ("発売中", "受付中")) else "check"

    def safe(value: str) -> str:
        return clean(value).replace("|", "／").replace("\n", " ").replace("`", "'")

    return "|".join([
        date, safe(open_time), safe(start_time), safe(venue), safe(area), safe(title), genre,
        status, price, safe(price_text), safe(performers), url,
    ])


def dedupe_key(row: str) -> tuple[str, str, str, str]:
    parts = row.split("|")
    return parts[0], parts[2], parts[3], parts[5]


def main() -> None:
    # GitHub-hosted runner is UTC; use JST explicitly so the "past event" boundary
    # does not lag nine hours.
    now_jst = datetime.utcnow() + timedelta(hours=9)
    today = now_jst.strftime("%Y-%m-%d")
    horizon = (now_jst + timedelta(days=180)).strftime("%Y-%m-%d")

    links = find_detail_links()
    rows_by_key: dict[tuple[str, str, str, str], str] = {}
    errors = 0

    for index, (url, (venue, area)) in enumerate(sorted(links.items()), start=1):
        try:
            row = parse_detail(url, venue, area, today, horizon)
            if row:
                rows_by_key[dedupe_key(row)] = row
        except Exception as exc:
            errors += 1
            print(f"WARN detail {url}: {exc}")
        if index % 25 == 0:
            time.sleep(0.3)

    ordered = sorted(rows_by_key.values(), key=lambda row: (row.split("|")[0], row.split("|")[2], row.split("|")[3], row.split("|")[5]))

    # Do not replace a previously healthy auto-data file with an empty result when
    # FANY has a temporary outage / markup failure.
    if not ordered and OUT.exists():
        print(f"ERROR: scraper returned 0 events ({errors} detail errors); keeping existing {OUT}")
        return

    body = "\n".join(ordered)
    OUT.write_text(
        "(() => {\n"
        "  \"use strict\";\n"
        "  const autoRows = String.raw`\n" + body + "`;\n"
        "  const current = String(window.YOSHIMOTO_LIVE_ROWS || \"\").trim();\n"
        "  window.YOSHIMOTO_LIVE_ROWS = `${current}\\n${autoRows.trim()}`.trim();\n"
        "  window.YOSHIMOTO_AUTO_UPDATED_AT = \"" + now_jst.strftime("%Y-%m-%d %H:%M JST") + "\";\n"
        "})();\n",
        encoding="utf-8",
    )
    print(f"updated {OUT}: {len(ordered)} events from {len(links)} detail links, {errors} detail errors")


if __name__ == "__main__":
    main()
