window.COMEDY_SHOW_CALENDAR = {
  meta: {
    version: "1.0.0",
    updatedAt: "2026-08-09T21:00:00+09:00",
    defaultWeek: "2026-08-10",
    coverageLabel: "2026.08",
    timezone: "Asia/Tokyo",
    note: "放送局・番組公式サイトで確認できた情報を優先しています。『通常枠』は休止・時間変更の可能性があります。"
  },
  broadcasts: [
    {
      id: "yoshimoto-20260808",
      seriesId: "yoshimoto-shinkigeki",
      title: "よしもと新喜劇",
      episodeTitle: "中古住宅は愛がいっぱい！？",
      date: "2026-08-08",
      startTime: "12:54",
      endTime: "13:54",
      startsAt: "2026-08-08T12:54:00+09:00",
      endsAt: "2026-08-08T13:54:00+09:00",
      station: "MBS毎日放送",
      region: "関西ローカル",
      status: "confirmed",
      statusLabel: "放送済み",
      genres: ["新喜劇", "コメディ劇"],
      mark: "新喜劇",
      accent: "#ed553b",
      summary: "舞台の新喜劇を丸ごと楽しめる、土曜昼の定番。東京からはTVerの見逃し配信で視聴できます。",
      cast: ["酒井藍", "辻本茂雄", "島田珠代", "池乃めだか", "西川忠志", "Mr.オクレ", "島田一の介", "レイチェル"],
      media: [
        { kind: "tv-local", label: "MBS", note: "関西ローカル", url: "https://www.mbs.jp/shinkigeki/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srcu1c6j4c" }
      ],
      officialUrl: "https://www.mbs.jp/shinkigeki/",
      sourceUrl: "https://shinkigeki.yoshimoto.co.jp/media"
    },
    {
      id: "chaplin-20260808",
      seriesId: "nichiyou-chaplin",
      title: "すっかり にちようチャップリン",
      episodeTitle: "出るかもチャップリン 完結編",
      date: "2026-08-08",
      startTime: "24:25",
      endTime: "24:55",
      startsAt: "2026-08-09T00:25:00+09:00",
      endsAt: "2026-08-09T00:55:00+09:00",
      station: "テレビ東京",
      region: "関東ほか",
      status: "confirmed",
      statusLabel: "放送済み",
      genres: ["漫才", "コント", "発掘"],
      mark: "CHAP",
      accent: "#7c3aed",
      summary: "若手から実力派までがノンストップでネタを披露する純ネタ番組。",
      cast: ["内村光良", "土田晃之", "千鳥", "ハリセンボン", "井戸田潤", "田中卓志", "アメリカンBBチキン", "きつね日和", "承子クラーケン", "ツーナッカン", "マウンテンブック", "ゆずの花"],
      media: [
        { kind: "tv-tokyo", label: "テレビ東京", note: "地上波", url: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srxlbxo3k8" }
      ],
      officialUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/",
      sourceUrl: "https://bangumi.org/tv_events/seasons?season_id=921796"
    },
    {
      id: "engei-zukan-20260809",
      seriesId: "engei-zukan",
      title: "桂文珍の演芸図鑑",
      episodeTitle: "由紀さおり／ロケット団／入船亭扇橋",
      date: "2026-08-09",
      startTime: "05:20",
      endTime: "05:50",
      startsAt: "2026-08-09T05:20:00+09:00",
      endsAt: "2026-08-09T05:50:00+09:00",
      station: "NHK総合",
      region: "全国",
      status: "confirmed",
      statusLabel: "放送済み",
      genres: ["漫才", "落語", "演芸"],
      mark: "演芸",
      accent: "#a16207",
      summary: "漫才・落語など東西の名人芸と、ゲスト対談を落ち着いて楽しめる朝の演芸番組。",
      cast: ["桂文珍", "由紀さおり", "ロケット団", "入船亭扇橋"],
      media: [
        { kind: "tv-national", label: "NHK総合", note: "全国", url: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/" }
      ],
      officialUrl: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/",
      sourceUrl: "https://thetv.jp/program/0000996203/"
    },
    {
      id: "shoten-20260809",
      seriesId: "shoten",
      title: "笑点",
      episodeTitle: "好楽さん80歳の誕生日おめでとう！",
      date: "2026-08-09",
      startTime: "17:30",
      endTime: "18:00",
      startsAt: "2026-08-09T17:30:00+09:00",
      endsAt: "2026-08-09T18:00:00+09:00",
      station: "日本テレビ系",
      region: "全国",
      status: "confirmed",
      statusLabel: "放送済み",
      genres: ["大喜利", "演芸"],
      mark: "笑点",
      accent: "#d97706",
      summary: "前半の演芸と後半の大喜利を楽しむ長寿番組。TVerは最新回、Huluは過去回も視聴できます。",
      cast: ["春風亭昇太", "三遊亭好楽", "三遊亭小遊三", "林家たい平", "立川晴の輔", "春風亭一之輔", "桂宮治", "山田隆夫", "TOKYO COOL"],
      media: [
        { kind: "tv-national", label: "日テレ系", note: "全国", url: "https://www.ntv.co.jp/sho-ten/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/sri2z21ox3" },
        { kind: "paid", label: "Hulu", note: "過去回あり", url: "https://www.hulu.jp/shoten/" }
      ],
      officialUrl: "https://www.ntv.co.jp/sho-ten/",
      sourceUrl: "https://www.ntv.co.jp/sho-ten/"
    },
    {
      id: "zaou-20260814",
      seriesId: "zaou",
      title: "千原ジュニアの座王",
      episodeTitle: "ショートネタの笑いの総合格闘技",
      date: "2026-08-14",
      startTime: "24:45",
      endTime: "25:15",
      startsAt: "2026-08-15T00:45:00+09:00",
      endsAt: "2026-08-15T01:15:00+09:00",
      station: "カンテレ",
      region: "関西ローカル",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["大喜利", "ギャグ", "モノボケ"],
      mark: "座王",
      accent: "#dc2626",
      summary: "椅子取りゲームと、大喜利・ギャグ・モノボケなどを組み合わせた即興ネタ対決。東京からはTVerで視聴できます。",
      cast: ["千原ジュニア", "竹上萌奈", "審査委員長・プレイヤーは発表待ち"],
      media: [
        { kind: "tv-local", label: "カンテレ", note: "関西ローカル", url: "https://www.ktv.jp/zao/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srz0rjdh54" }
      ],
      officialUrl: "https://www.ktv.jp/zao/",
      sourceUrl: "https://www.ktv.jp/zao/"
    },
    {
      id: "yoshimoto-20260815",
      seriesId: "yoshimoto-shinkigeki",
      title: "よしもと新喜劇",
      episodeTitle: "高いところから失礼します！？",
      date: "2026-08-15",
      startTime: "12:54",
      endTime: "13:54",
      startsAt: "2026-08-15T12:54:00+09:00",
      endsAt: "2026-08-15T13:54:00+09:00",
      station: "MBS毎日放送",
      region: "関西ローカル",
      status: "confirmed",
      statusLabel: "放送確定",
      genres: ["新喜劇", "コメディ劇"],
      mark: "新喜劇",
      accent: "#ed553b",
      summary: "閉園間近のデパート屋上遊園地で、裕たちが娘のためにヒーローショーを復活させようと奮闘します。",
      cast: ["吉田裕", "松浦真也", "森田まりこ", "西川忠志", "千葉公平", "諸見里大介", "レイチェル", "カバ", "小西武蔵", "服部ひで子", "小林ゆう", "安尾信乃助", "入澤弘喜", "おやどまり", "岡田直子", "立花えこ", "辻本茂雄", "内場勝則"],
      media: [
        { kind: "tv-local", label: "MBS", note: "関西ローカル", url: "https://www.mbs.jp/shinkigeki/" },
        { kind: "free", label: "TVer", note: "東京から無料", url: "https://tver.jp/series/srcu1c6j4c" }
      ],
      officialUrl: "https://www.mbs.jp/shinkigeki/",
      sourceUrl: "https://www.mbs.jp/shinkigeki/"
    },
    {
      id: "new-key-20260815",
      seriesId: "new-key",
      title: "新しいカギ",
      episodeTitle: "学校かくれんぼ 2週連続SP・第1夜",
      date: "2026-08-15",
      startTime: "18:30",
      endTime: "21:00",
      startsAt: "2026-08-15T18:30:00+09:00",
      endsAt: "2026-08-15T21:00:00+09:00",
      station: "フジテレビ系",
      region: "全国（一部地域を除く）",
      status: "confirmed",
      statusLabel: "放送確定",
      genres: ["企画", "コント", "総合お笑い"],
      mark: "NEW",
      accent: "#2563eb",
      summary: "浜松修学舎を舞台に、カギチームとバレーボール男子日本代表が約1000人の生徒から本気で隠れます。",
      cast: ["霜降り明星", "チョコレートプラネット", "ハナコ", "髙橋藍", "小野寺太志", "髙橋健太郎", "大塚達宣"],
      media: [
        { kind: "tv-national", label: "フジ系", note: "地上波", url: "https://www.fujitv.co.jp/newkey/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srt435gfnc" },
        { kind: "paid", label: "FOD", note: "配信", url: "https://fod.fujitv.co.jp/title/2705/" }
      ],
      officialUrl: "https://www.fujitv.co.jp/newkey/",
      sourceUrl: "https://www.fujitv.co.jp/fujitv/news/20260774.html"
    },
    {
      id: "chaplin-20260815",
      seriesId: "nichiyou-chaplin",
      title: "すっかり にちようチャップリン",
      episodeTitle: "今週の出演芸人は発表待ち",
      date: "2026-08-15",
      startTime: "24:25",
      endTime: "24:55",
      startsAt: "2026-08-16T00:25:00+09:00",
      endsAt: "2026-08-16T00:55:00+09:00",
      station: "テレビ東京",
      region: "関東ほか",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["漫才", "コント", "発掘"],
      mark: "CHAP",
      accent: "#7c3aed",
      summary: "内村光良と実力派レギュラー陣が見届ける、30分のノンストップお笑いライブ。",
      cast: ["内村光良", "土田晃之", "千鳥", "ハリセンボン", "井戸田潤", "田中卓志", "出演芸人は発表待ち"],
      media: [
        { kind: "tv-tokyo", label: "テレビ東京", note: "地上波", url: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srxlbxo3k8" }
      ],
      officialUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/",
      sourceUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/"
    },
    {
      id: "engei-zukan-20260816",
      seriesId: "engei-zukan",
      title: "桂文珍の演芸図鑑",
      episodeTitle: "由紀さおり／林家楽一／三遊亭わん丈",
      date: "2026-08-16",
      startTime: "05:20",
      endTime: "05:50",
      startsAt: "2026-08-16T05:20:00+09:00",
      endsAt: "2026-08-16T05:50:00+09:00",
      station: "NHK総合",
      region: "全国",
      status: "confirmed",
      statusLabel: "放送確定",
      genres: ["落語", "紙切り", "演芸"],
      mark: "演芸",
      accent: "#a16207",
      summary: "林家楽一の紙切り、三遊亭わん丈の落語と、桂文珍・由紀さおりの対談を届けます。",
      cast: ["桂文珍", "由紀さおり", "林家楽一", "三遊亭わん丈"],
      media: [
        { kind: "tv-national", label: "NHK総合", note: "全国", url: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/" }
      ],
      officialUrl: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/",
      sourceUrl: "https://thetv.jp/program/0000996203/"
    },
    {
      id: "shoten-20260816",
      seriesId: "shoten",
      title: "笑点",
      episodeTitle: "演芸＋大喜利",
      date: "2026-08-16",
      startTime: "17:30",
      endTime: "18:00",
      startsAt: "2026-08-16T17:30:00+09:00",
      endsAt: "2026-08-16T18:00:00+09:00",
      station: "日本テレビ系",
      region: "全国",
      status: "confirmed",
      statusLabel: "放送確定",
      genres: ["大喜利", "演芸"],
      mark: "笑点",
      accent: "#d97706",
      summary: "演芸ゲストと、春風亭昇太司会の大喜利。演芸出演者は番組表で未発表です。",
      cast: ["春風亭昇太", "三遊亭好楽", "三遊亭小遊三", "林家たい平", "立川晴の輔", "春風亭一之輔", "桂宮治", "山田隆夫"],
      media: [
        { kind: "tv-national", label: "日テレ系", note: "全国", url: "https://www.ntv.co.jp/sho-ten/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/sri2z21ox3" },
        { kind: "paid", label: "Hulu", note: "過去回あり", url: "https://www.hulu.jp/shoten/" }
      ],
      officialUrl: "https://www.ntv.co.jp/sho-ten/",
      sourceUrl: "https://bangumi.org/tv_events/seasons?season_id=236"
    },
    {
      id: "ariyoshi-wall-20260819",
      seriesId: "ariyoshi-wall",
      title: "有吉の壁",
      episodeTitle: "壁芸人35組・サバイバルネタバトル",
      date: "2026-08-19",
      startTime: "19:00",
      endTime: "20:00",
      startsAt: "2026-08-19T19:00:00+09:00",
      endsAt: "2026-08-19T20:00:00+09:00",
      station: "日本テレビ系",
      region: "全国",
      status: "confirmed",
      statusLabel: "放送確定",
      genres: ["即興コント", "ネタバトル"],
      mark: "壁",
      accent: "#0891b2",
      summary: "有吉弘行を笑わせるため、壁芸人がさまざまなシチュエーションで即興ネタに挑みます。終了時刻は番組表で要確認。",
      cast: ["有吉弘行", "佐藤栞里", "壁芸人35組"],
      media: [
        { kind: "tv-national", label: "日テレ系", note: "地上波", url: "https://www.ntv.co.jp/ariyoshinokabe/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srxjstc489" },
        { kind: "paid", label: "Hulu", note: "過去回あり", url: "https://www.hulu.jp/ariyoshi-no-kabe" }
      ],
      officialUrl: "https://www.ntv.co.jp/ariyoshinokabe/",
      sourceUrl: "https://www.ntv.co.jp/ariyoshinokabe/articles/7613sf284y2d1sjzc19.html"
    },
    {
      id: "zaou-20260821",
      seriesId: "zaou",
      title: "千原ジュニアの座王",
      episodeTitle: "出演者は発表待ち",
      date: "2026-08-21",
      startTime: "24:45",
      endTime: "25:15",
      startsAt: "2026-08-22T00:45:00+09:00",
      endsAt: "2026-08-22T01:15:00+09:00",
      station: "カンテレ",
      region: "関西ローカル",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["大喜利", "ギャグ", "モノボケ"],
      mark: "座王",
      accent: "#dc2626",
      summary: "即興力で競うショートネタ対決。東京からはTVerの見逃し配信で視聴できます。",
      cast: ["千原ジュニア", "竹上萌奈", "審査委員長・プレイヤーは発表待ち"],
      media: [
        { kind: "tv-local", label: "カンテレ", note: "関西ローカル", url: "https://www.ktv.jp/zao/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srz0rjdh54" }
      ],
      officialUrl: "https://www.ktv.jp/zao/",
      sourceUrl: "https://www.ktv.jp/zao/"
    },
    {
      id: "new-key-20260822",
      seriesId: "new-key",
      title: "新しいカギ",
      episodeTitle: "学校かくれんぼ 2週連続SP・第2夜",
      date: "2026-08-22",
      startTime: "18:30",
      endTime: "21:00",
      startsAt: "2026-08-22T18:30:00+09:00",
      endsAt: "2026-08-22T21:00:00+09:00",
      station: "フジテレビ系",
      region: "全国（一部地域を除く）",
      status: "confirmed",
      statusLabel: "放送確定",
      genres: ["企画", "コント", "総合お笑い"],
      mark: "NEW",
      accent: "#2563eb",
      summary: "中央大学附属を舞台に、生徒約1700人とカギチームが対決。鈴鹿央士とCANDY TUNEが初参戦します。",
      cast: ["霜降り明星", "チョコレートプラネット", "ハナコ", "鈴鹿央士", "CANDY TUNE", "スカチャン"],
      media: [
        { kind: "tv-national", label: "フジ系", note: "地上波", url: "https://www.fujitv.co.jp/newkey/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srt435gfnc" },
        { kind: "paid", label: "FOD", note: "配信", url: "https://fod.fujitv.co.jp/title/2705/" }
      ],
      officialUrl: "https://www.fujitv.co.jp/newkey/",
      sourceUrl: "https://www.fujitv.co.jp/fujitv/news/20260774.html"
    },
    {
      id: "chaplin-20260822",
      seriesId: "nichiyou-chaplin",
      title: "すっかり にちようチャップリン",
      episodeTitle: "出演芸人は発表待ち",
      date: "2026-08-22",
      startTime: "24:25",
      endTime: "24:55",
      startsAt: "2026-08-23T00:25:00+09:00",
      endsAt: "2026-08-23T00:55:00+09:00",
      station: "テレビ東京",
      region: "関東ほか",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["漫才", "コント", "発掘"],
      mark: "CHAP",
      accent: "#7c3aed",
      summary: "今イチバン面白い芸人たちが集まる、ノンストップお笑いライブ。",
      cast: ["内村光良", "土田晃之", "千鳥", "ハリセンボン", "井戸田潤", "田中卓志", "出演芸人は発表待ち"],
      media: [
        { kind: "tv-tokyo", label: "テレビ東京", note: "地上波", url: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srxlbxo3k8" }
      ],
      officialUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/",
      sourceUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/"
    },
    {
      id: "engei-zukan-20260823",
      seriesId: "engei-zukan",
      title: "演芸図鑑",
      episodeTitle: "出演者は発表待ち",
      date: "2026-08-23",
      startTime: "05:20",
      endTime: "05:50",
      startsAt: "2026-08-23T05:20:00+09:00",
      endsAt: "2026-08-23T05:50:00+09:00",
      station: "NHK総合",
      region: "全国",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["漫才", "落語", "演芸"],
      mark: "演芸",
      accent: "#a16207",
      summary: "東西の達人による演芸と、豪華ゲストとの対談。",
      cast: ["出演者は発表待ち"],
      media: [
        { kind: "tv-national", label: "NHK総合", note: "全国", url: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/" }
      ],
      officialUrl: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/",
      sourceUrl: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/"
    },
    {
      id: "shoten-20260823",
      seriesId: "shoten",
      title: "笑点",
      episodeTitle: "演芸＋大喜利",
      date: "2026-08-23",
      startTime: "17:30",
      endTime: "18:00",
      startsAt: "2026-08-23T17:30:00+09:00",
      endsAt: "2026-08-23T18:00:00+09:00",
      station: "日本テレビ系",
      region: "全国",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["大喜利", "演芸"],
      mark: "笑点",
      accent: "#d97706",
      summary: "前半の演芸と後半の大喜利。演芸出演者は発表待ちです。",
      cast: ["春風亭昇太", "三遊亭好楽", "三遊亭小遊三", "林家たい平", "立川晴の輔", "春風亭一之輔", "桂宮治", "山田隆夫"],
      media: [
        { kind: "tv-national", label: "日テレ系", note: "全国", url: "https://www.ntv.co.jp/sho-ten/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/sri2z21ox3" },
        { kind: "paid", label: "Hulu", note: "過去回あり", url: "https://www.hulu.jp/shoten/" }
      ],
      officialUrl: "https://www.ntv.co.jp/sho-ten/",
      sourceUrl: "https://www.ntv.co.jp/sho-ten/"
    },
    {
      id: "ariyoshi-wall-20260826",
      seriesId: "ariyoshi-wall",
      title: "有吉の壁",
      episodeTitle: "出演者・企画詳細は発表待ち",
      date: "2026-08-26",
      startTime: "19:00",
      endTime: "20:00",
      startsAt: "2026-08-26T19:00:00+09:00",
      endsAt: "2026-08-26T20:00:00+09:00",
      station: "日本テレビ系",
      region: "全国",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["即興コント", "ネタバトル"],
      mark: "壁",
      accent: "#0891b2",
      summary: "壁芸人が即興ネタで有吉弘行に挑戦。放送内容と終了時刻は公式の次回予告で確認できます。",
      cast: ["有吉弘行", "佐藤栞里", "壁芸人の皆様"],
      media: [
        { kind: "tv-national", label: "日テレ系", note: "地上波", url: "https://www.ntv.co.jp/ariyoshinokabe/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srxjstc489" },
        { kind: "paid", label: "Hulu", note: "過去回あり", url: "https://www.hulu.jp/ariyoshi-no-kabe" }
      ],
      officialUrl: "https://www.ntv.co.jp/ariyoshinokabe/",
      sourceUrl: "https://www.ntv.co.jp/ariyoshinokabe/"
    },
    {
      id: "zaou-20260828",
      seriesId: "zaou",
      title: "千原ジュニアの座王",
      episodeTitle: "出演者は発表待ち",
      date: "2026-08-28",
      startTime: "24:45",
      endTime: "25:15",
      startsAt: "2026-08-29T00:45:00+09:00",
      endsAt: "2026-08-29T01:15:00+09:00",
      station: "カンテレ",
      region: "関西ローカル",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["大喜利", "ギャグ", "モノボケ"],
      mark: "座王",
      accent: "#dc2626",
      summary: "即興力で競うショートネタ対決。東京からはTVerの見逃し配信で視聴できます。",
      cast: ["千原ジュニア", "竹上萌奈", "審査委員長・プレイヤーは発表待ち"],
      media: [
        { kind: "tv-local", label: "カンテレ", note: "関西ローカル", url: "https://www.ktv.jp/zao/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srz0rjdh54" }
      ],
      officialUrl: "https://www.ktv.jp/zao/",
      sourceUrl: "https://www.ktv.jp/zao/"
    },
    {
      id: "yoshimoto-20260829",
      seriesId: "yoshimoto-shinkigeki",
      title: "よしもと新喜劇",
      episodeTitle: "出演者・演目は発表待ち",
      date: "2026-08-29",
      startTime: "12:54",
      endTime: "13:54",
      startsAt: "2026-08-29T12:54:00+09:00",
      endsAt: "2026-08-29T13:54:00+09:00",
      station: "MBS毎日放送",
      region: "関西ローカル",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["新喜劇", "コメディ劇"],
      mark: "新喜劇",
      accent: "#ed553b",
      summary: "舞台の新喜劇をテレビで。東京からはTVerの見逃し配信で視聴できます。",
      cast: ["出演者は発表待ち"],
      media: [
        { kind: "tv-local", label: "MBS", note: "関西ローカル", url: "https://www.mbs.jp/shinkigeki/" },
        { kind: "free", label: "TVer", note: "東京から無料", url: "https://tver.jp/series/srcu1c6j4c" }
      ],
      officialUrl: "https://www.mbs.jp/shinkigeki/",
      sourceUrl: "https://www.mbs.jp/shinkigeki/"
    },
    {
      id: "chaplin-20260829",
      seriesId: "nichiyou-chaplin",
      title: "すっかり にちようチャップリン",
      episodeTitle: "出演芸人は発表待ち",
      date: "2026-08-29",
      startTime: "24:25",
      endTime: "24:55",
      startsAt: "2026-08-30T00:25:00+09:00",
      endsAt: "2026-08-30T00:55:00+09:00",
      station: "テレビ東京",
      region: "関東ほか",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["漫才", "コント", "発掘"],
      mark: "CHAP",
      accent: "#7c3aed",
      summary: "今イチバン面白い芸人たちが集まる、ノンストップお笑いライブ。",
      cast: ["内村光良", "土田晃之", "千鳥", "ハリセンボン", "井戸田潤", "田中卓志", "出演芸人は発表待ち"],
      media: [
        { kind: "tv-tokyo", label: "テレビ東京", note: "地上波", url: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/srxlbxo3k8" }
      ],
      officialUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/",
      sourceUrl: "https://www.tv-tokyo.co.jp/nichiyou_chaplin/"
    },
    {
      id: "engei-zukan-20260830",
      seriesId: "engei-zukan",
      title: "演芸図鑑",
      episodeTitle: "出演者は発表待ち",
      date: "2026-08-30",
      startTime: "05:20",
      endTime: "05:50",
      startsAt: "2026-08-30T05:20:00+09:00",
      endsAt: "2026-08-30T05:50:00+09:00",
      station: "NHK総合",
      region: "全国",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["漫才", "落語", "演芸"],
      mark: "演芸",
      accent: "#a16207",
      summary: "東西の達人による演芸と、豪華ゲストとの対談。",
      cast: ["出演者は発表待ち"],
      media: [
        { kind: "tv-national", label: "NHK総合", note: "全国", url: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/" }
      ],
      officialUrl: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/",
      sourceUrl: "https://www.nhk.jp/p/ts/Q3GYZ14GLY/"
    },
    {
      id: "shoten-20260830",
      seriesId: "shoten",
      title: "笑点",
      episodeTitle: "演芸＋大喜利",
      date: "2026-08-30",
      startTime: "17:30",
      endTime: "18:00",
      startsAt: "2026-08-30T17:30:00+09:00",
      endsAt: "2026-08-30T18:00:00+09:00",
      station: "日本テレビ系",
      region: "全国",
      status: "regular",
      statusLabel: "通常枠",
      genres: ["大喜利", "演芸"],
      mark: "笑点",
      accent: "#d97706",
      summary: "前半の演芸と後半の大喜利。演芸出演者は発表待ちです。",
      cast: ["春風亭昇太", "三遊亭好楽", "三遊亭小遊三", "林家たい平", "立川晴の輔", "春風亭一之輔", "桂宮治", "山田隆夫"],
      media: [
        { kind: "tv-national", label: "日テレ系", note: "全国", url: "https://www.ntv.co.jp/sho-ten/" },
        { kind: "free", label: "TVer", note: "見逃し無料", url: "https://tver.jp/series/sri2z21ox3" },
        { kind: "paid", label: "Hulu", note: "過去回あり", url: "https://www.hulu.jp/shoten/" }
      ],
      officialUrl: "https://www.ntv.co.jp/sho-ten/",
      sourceUrl: "https://www.ntv.co.jp/sho-ten/"
    }
  ],
  watchlist: [
    {
      id: "netapare-premium",
      title: "ネタパレ THE プレミアム",
      lastAired: "2026-06-20",
      status: "次回放送待ち",
      genres: ["ショートネタ", "モノマネ", "コント"],
      cast: ["南原清隆", "陣内智則", "増田貴久"],
      media: ["フジテレビ系", "FOD"],
      officialUrl: "https://www.fujitv.co.jp/netapare/",
      streamUrl: "https://fod.fujitv.co.jp/title/2738/",
      accent: "#e11d48",
      mark: "ネタ"
    },
    {
      id: "kusesugo",
      title: "千鳥のクセスゴ！",
      lastAired: "2026-07-04",
      status: "次回特番待ち",
      genres: ["クセネタ", "コラボ", "モノマネ"],
      cast: ["千鳥"],
      media: ["フジテレビ系", "TVer", "FOD"],
      officialUrl: "https://www.fujitv.co.jp/kusesugo/",
      accent: "#db2777",
      mark: "クセ"
    },
    {
      id: "engei-grand-slam",
      title: "ENGEIグランドスラム",
      lastAired: "2026-08-01",
      status: "次回放送待ち",
      genres: ["漫才", "コント", "ピン芸"],
      cast: ["ナインティナイン", "松岡茉優"],
      media: ["フジテレビ系", "TVer", "FOD"],
      officialUrl: "https://www.fujitv.co.jp/engei/",
      accent: "#ea580c",
      mark: "ENGEI"
    },
    {
      id: "red-carpet",
      title: "爆笑レッドカーペット",
      lastAired: "2026-08-01",
      status: "次回放送待ち",
      genres: ["ショートネタ", "漫才", "コント"],
      cast: ["今田耕司", "高橋克実"],
      media: ["フジテレビ系", "TVer", "FOD"],
      officialUrl: "https://www.fujitv.co.jp/fujitv/news/20260827.html",
      accent: "#b91c1c",
      mark: "RED"
    },
    {
      id: "double-impact",
      title: "ダブルインパクト",
      lastAired: "2026-07-20",
      status: "2027大会待ち",
      genres: ["漫才", "コント", "賞レース"],
      cast: ["漫才＆コント二刀流芸人"],
      media: ["日本テレビ系", "TVer", "Hulu", "YouTube"],
      officialUrl: "https://www.ntv.co.jp/double-impact/",
      accent: "#111827",
      mark: "W"
    }
  ]
};
